version: '3' # composeファイルのバーション指定
services:
  app:
    build: .
    tty: true # コンテナの起動永続化
    volumes:
      - ./src/fril-search:/usr/src/fril-search
    ports:
      # TODO: port決め
      - '9001:3000'
